import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/localization_service.dart';

class AppLocalizations {
  static AppLocalizations? _instance;
  static AppLocalizations get instance => _instance ??= AppLocalizations._();
  
  AppLocalizations._();
  
  // Get localized string based on current locale
  static String of(BuildContext context, String key) {
    final localizationService = Provider.of<LocalizationService>(context, listen: false);
    final locale = localizationService.currentLocale.languageCode;
    
    // Simple localization map - in a real app, you'd use proper localization packages
    final translations = _getTranslations(locale);
    return translations[key] ?? key;
  }
  
  // Get translations for a specific locale
  static Map<String, String> _getTranslations(String locale) {
    switch (locale) {
      case 'fr':
        return _frenchTranslations;
      case 'en':
      default:
        return _englishTranslations;
    }
  }
  
  // English translations
  static const Map<String, String> _englishTranslations = {
    'appTitle': 'Entrix Scanner',
    'accessControlSystem': 'Access Control System',
    'loginTitle': 'Login',
    'login': 'Login',
    'signIn': 'Sign In',
    'loading': 'Loading...',
    'email': 'Email',
    'password': 'Password',
    'enterYourPassword': 'Enter your password',
    'enterYourUsername': 'Enter your username',
    'enterYourEmail': 'Enter your email',
    'emailRequired': 'Email is required',
    'passwordRequired': 'Password is required',
    'passwordTooShort': 'Password must be at least 6 characters',
    'invalidEmail': 'Please enter a valid email',
    'loginFailed': 'Login failed',
    'loginSuccess': 'Login successful',
    'dashboard': 'Dashboard',
    'startScanning': 'Start Scanning',
    'history': 'History',
    'statistics': 'Statistics',
    'successRate': 'Success Rate',
    'scanQRCode': 'Scan QR Code',
    'scanning': 'Scanning...',
    'scanSuccess': 'Scan Successful',
    'scanFailed': 'Scan Failed',
    'accessGranted': 'Access Granted',
    'validQRNoSubscription': 'Valid QR - No Subscription',
    'qrCodeNotFound': 'This QR code does not exist in our system.',
    'infoMode': 'Info Mode',
    'infoModeScan': 'Info Mode Scan',
    'infoRetrieved': 'QR code found - Info retrieved',
    'noMetadata': 'QR code found - No metadata available',
    'infoScanFailed': 'Info mode scan failed',
    'qrCodeNotFoundInSystem': 'QR code not found in system',
    'infoModeScanError': 'Info mode scan error',
    'accessInformation': 'Access Information',
    'accessDeniedReason': 'Access Denied Reason',
    'lastScanInformation': 'Last Scan Information',
    'lastScanDate': 'Last Scan Date',
    'scannedBy': 'Scanned By',
    'status': 'Status',
    'reason': 'Reason',
    'message': 'Message',
    'planName': 'Plan Name',
    'zoneName': 'Zone',
    'seatNumber': 'Seat',
    'entryGate': 'Entry Gate',
    'userName': 'User Name',
    'return': 'Return',
    'delete': 'Delete',
    'search': 'Search',
    'searchHint': 'Enter serial number, QR code, or message',
    'filterByStatus': 'Filter by Status',
    'recordDeleted': 'Record deleted',
    'errorDeletingRecord': 'Error deleting record',
    'pleaseEnterQRCode': 'Please enter a QR code',
    'enterQRCode': 'Enter QR Code',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'settings': 'Settings',
    'language': 'Language',
    'english': 'English',
    'french': 'French',
    'logout': 'Logout',
    'logoutConfirm': 'Are you sure you want to logout?',
    'yes': 'Yes',
    'no': 'No',
    'about': 'About',
    'version': 'Version',
    'buildNumber': 'Build Number',
    'deviceInfo': 'Device Information',
    'deviceModel': 'Device Model',
    'osVersion': 'OS Version',
    'flutterVersion': 'Flutter Version',
    'dartVersion': 'Dart Version',
    'close': 'Close',
    'noRecordsFound': 'No records found',
    'clearHistory': 'Clear History',
    'clearHistoryConfirm': 'Are you sure you want to clear all scan history?',
    'historyCleared': 'History cleared',
    'errorClearingHistory': 'Error clearing history',
    'exportHistory': 'Export History',
    'csvExportReady': 'CSV export ready ({0} characters)',
    'errorExportingCsv': 'Error exporting CSV: {0}',
    'qrCodeScanned': 'QR code scanned: {0}',
    'errorScanningQrCode': 'Error scanning QR code: {0}',
    'errorValidatingQrCode': 'Error validating QR code: {0}',
    'noSpecificAccessInfo': 'No specific access information available for this case.',
    'errorWithDetails': 'Error: {0}',
    'qrCode': 'QR Code',
    'result': 'Result',
    'timestamp': 'Timestamp',
    'agent': 'Agent',
    'event': 'Event',
    'venue': 'Venue',
    'subscriptionInfo': 'Subscription Information',
    'userInfo': 'User Information',
    'accessPoint': 'Access Point',
    'price': 'Price',
    'currency': 'Currency',
    'holderName': 'Holder Name',
    'scanResult': 'Scan Result',
    'validationTime': 'Validation Time',
    'denialDetails': 'Denial Details',
    'lastUsage': 'Last Usage',
    'entryPoint': 'Entry Point',
    'primaryReason': 'Primary Reason',
    'technicalReason': 'Technical Reason',
    'suggestedActions': 'Suggested Actions',
    'contactInfo': 'Contact Information',
    'supervisorPhone': 'Supervisor Phone',
    'customerService': 'Customer Service',
    'justNow': 'Just now',
    'minutesAgo': 'minutes ago',
    'hoursAgo': 'hours ago',
    'hourAgo': 'hour ago',
    'at': 'at',
    'unknown': 'Unknown',
    'notAvailable': 'N/A',
    'noPlan': 'No Plan',
    'noData': 'No Data',
    'scanningInProgress': 'Scanning in progress...',
    'pleaseWait': 'Please wait...',
    'connectionError': 'Connection Error',
    'networkUnavailable': 'Network is unavailable',
    'tryAgain': 'Try Again',
    'refresh': 'Refresh',
    'pullToRefresh': 'Pull to refresh',
    'lastUpdated': 'Last updated',
    'noInternetConnection': 'No internet connection',
    'checkConnection': 'Please check your internet connection and try again',
    'timeout': 'Request timeout',
    'serverError': 'Server error',
    'badRequest': 'Bad request',
    'unauthorized': 'Unauthorized',
    'forbidden': 'Forbidden',
    'notFound': 'Not found',
    'internalServerError': 'Internal server error',
    'serviceUnavailable': 'Service unavailable',
    'currentEvent': 'Current Event',
    'eventName': 'Event Name',
    'eventDescription': 'Event Description',
    'noActiveEventsFound': 'No active events found',
    'userProfile': 'User Profile',
    'accessLevel': 'Access Level',
    'agentId': 'Agent ID',
    'deviceInformation': 'Device Information',
    'appVersion': 'App Version',
    'lastLogin': 'Last Login',
    'sessionInfo': 'Session Information',
    'toggleMode': 'Toggle Mode',
    'flashOn': 'Flash On',
    'flashOff': 'Flash Off',
    'frontCamera': 'Front Camera',
    'backCamera': 'Back Camera',
    'scanCooldown': 'Scan Cooldown',
    'duplicateScan': 'Duplicate Scan',
    'scanTooFast': 'Please wait before scanning again',
    'cameraPermission': 'Camera Permission',
    'cameraPermissionRequired': 'Camera permission is required to scan QR codes',
    'grantPermission': 'Grant Permission',
    'permissionDenied': 'Permission Denied',
    'permissionPermanentlyDenied': 'Permission permanently denied',
    'openSettings': 'Open Settings',
    'validationResult': 'Validation Result',
    'backToScanner': 'Back to Scanner',
    'scanAgain': 'Scan Again',
    'scanNewCode': 'Scan New Code',
    'validationDetails': 'Validation Details',
    'accessGrantedTitle': 'Access Granted',
    'accessDeniedTitle': 'Access Denied',
    'infoModeTitle': 'Info Mode',
    'scanInformation': 'Scan Information',
    'debugLogs': 'Debug Logs',
    'scanHistory': 'Scan History',
    'scanStatistics': 'Scan Statistics',
    'totalRecords': 'Total Records',
    'filterRecords': 'Filter Records',
    'sortBy': 'Sort By',
    'sortByDate': 'Sort by Date',
    'sortByStatus': 'Sort by Status',
    'sortByAgent': 'Sort by Agent',
    'ascending': 'Ascending',
    'descending': 'Descending',
    'noScansToday': 'No scans today',
    'scansThisWeek': 'Scans this week',
    'scansThisMonth': 'Scans this month',
    'averageScanTime': 'Average scan time',
    'fastestScan': 'Fastest scan',
    'slowestScan': 'Slowest scan',
    'scanTrends': 'Scan Trends',
    'dailyStats': 'Daily Statistics',
    'weeklyStats': 'Weekly Statistics',
    'monthlyStats': 'Monthly Statistics',
    'contactAdministrator': 'Contact your administrator to set up events',
    'entrixScanner': 'Entrix Scanner',
    'errorLoadingHistory': 'Error loading scan history',
    'valid': 'Valid',
    'backToDashboard': 'Back to Dashboard',
    'codeLabel': 'Code:',
    'statusCodeLabel': 'Status Code:',
    'checkQRCodeValidation': '• The QR code is valid and not expired\n• You have proper authentication\n• The backend service is running\n• Network connection is available',
    'noActiveSubscription': 'No Active Subscription',
    'subscriptionExpired': 'Subscription Expired',
    'accessDenied': 'Access Denied',
    'codeNotRecognized': 'Code Not Recognized',
    'qrCodeNotValid': 'QR Code Not Valid',
    'startScanningToSeeHistory': 'Start scanning QR codes to see your history here',
    'alreadyUsed': 'Already Used',
    'expired': 'Expired',
    'all': 'All',
    'success': 'Success',
    'error': 'Error',
    'errorOccurred': 'Error occurred',
    'errorOccurredWithDetails': 'An error occurred: {0}',
    'warning': 'Warning',
    'infoModeLabel': 'Info Mode',
    'infoSuccess': 'Info Success',
    'infoNotFound': 'Info Not Found',
    'totalScans': 'Total',
    'successfulScans': 'Success',
    'failedScans': 'Failed',
    'infoScans': 'Info Mode',
    'todayScans': 'Today',
    'qrScanner': 'QR Scanner',
    'validationMode': 'Validation Mode',
    'infoOnlyMode': 'Info Only Mode',
    'infoModeOnly': 'Info Mode Only (Controller Role)',
    'enterQrCodeManually': 'Enter QR code manually',
    'checkInfo': 'Check Info',
    'validateQrCode': 'Validate QR Code',
    'instructions': 'Instructions',
    'pointCameraAtQrOrEnterManuallyToCheckSubscription': 'Point your camera at a QR code or enter the serial number to check subscription information',
    'pointCameraAtQrOrEnterManuallyToValidateAccess': 'Point your camera at a QR code or enter the serial number to validate access',
    'pointCameraAtQrOrEnterSerialNumberToCheckSubscription': 'Point your camera at a QR code or enter the serial number to check subscription information',
    'pointCameraAtQrOrEnterSerialNumberToValidateAccess': 'Point your camera at a QR code or enter the serial number to validate access',
    'controllerRoleInfoOnlyNoAccessValidation': 'Controller Role: Info mode only - no access validation',
    'infoOnly': 'Info Only',
    'validation': 'Validation',
    'role': 'Role',
    'scannerPaused': 'Scanner Paused',
    'switchCamera': 'Switch Camera',
    'scannerRefreshed': 'Scanner refreshed',
    'manualInput': 'Manual Input',
    'serialNumber': 'Serial Number',
    'enterSerialNumberManually': 'Enter 4-digit serial number',
    'validateSerialNumber': 'Validate Serial Number',
    'pleaseEnterSerialNumber': 'Please enter a serial number',
    'serialNumberMustBe4Digits': 'Serial number must be exactly 4 digits',
    'serialNumberNotFound': 'Serial number not found',
    'errorFindingSerialNumber': 'Error finding serial number',
    'searchRecords': 'Search Records',
    'enterSerialNumberOrQrCode': 'Enter serial number or QR code',
    'qrCodeNotRecognized': 'QR code not recognized',
    'codeExpired': 'Code expired',
    'wrongEvent': 'Wrong event',
    'wrongZone': 'Wrong zone',
    'wrongTime': 'Wrong time',
    'accessBlocked': 'Access blocked',
    'technicalError': 'Technical error',
    'conditionalAccess': 'Conditional access',
    'noMessage': 'No message'
  };
  
  // French translations
  static const Map<String, String> _frenchTranslations = {
    'appTitle': 'Entrix Scanner',
    'accessControlSystem': 'Système de contrôle d\'accès',
    'loginTitle': 'Connexion',
    'loading': 'Chargement...',
    'login': 'Connexion',
    'signIn': 'Connexion',
    'email': 'Email',
    'password': 'Mot de passe',
    'enterYourPassword': 'Entrez votre mot de passe',
    'enterYourUsername': 'Entrez votre nom d\'utilisateur',
    'enterYourEmail': 'Entrez votre email',
    'emailRequired': 'L\'email est requis',
    'passwordRequired': 'Le mot de passe est requis',
    'passwordTooShort': 'Le mot de passe doit comporter au moins 6 caractères',
    'invalidEmail': 'Veuillez entrer un email valide',
    'loginFailed': 'Échec de la connexion',
    'loginSuccess': 'Connexion réussie',
    'dashboard': 'Tableau de bord',
    'startScanning': 'Commencer le scan',
    'history': 'Historique',
    'statistics': 'Statistiques',
    'successRate': 'Taux de réussite',
    'scanQRCode': 'Scanner le QR Code',
    'scanning': 'Scan en cours...',
    'scanSuccess': 'Scan réussi',
    'scanFailed': 'Scan échoué',
    'accessGranted': 'Accès accordé',
    'validQRNoSubscription': 'QR valide - Pas d\'abonnement',
    'qrCodeNotFound': 'Ce QR code n\'existe pas dans notre système.',
    'infoMode': 'Mode info',
    'infoModeScan': 'Scan mode info',
    'infoRetrieved': 'QR code trouvé - Info récupérée',
    'noMetadata': 'QR code trouvé - Pas de métadonnées disponibles',
    'infoScanFailed': 'Échec du scan mode info',
    'qrCodeNotFoundInSystem': 'QR code non trouvé dans le système',
    'infoModeScanError': 'Erreur scan mode info',
    'accessInformation': 'Informations d\'accès',
    'accessDeniedReason': 'Raison du refus d\'accès',
    'lastScanInformation': 'Informations du dernier scan',
    'lastScanDate': 'Date du dernier scan',
    'scannedBy': 'Scanné par',
    'status': 'Statut',
    'reason': 'Raison',
    'message': 'Message',
    'ok': 'OK',
    'planName': 'Nom du plan',
    'zoneName': 'Zone',
    'seatNumber': 'Siège',
    'entryGate': 'Porte d\'entrée',
    'userName': 'Nom d\'utilisateur',
    'return': 'Retour',
    'delete': 'Supprimer',
    'search': 'Rechercher',
    'searchHint': 'Entrez le numéro de série, QR code ou message',
    'filterByStatus': 'Filtrer par statut',
    'recordDeleted': 'Enregistrement supprimé',
    'errorDeletingRecord': 'Erreur lors de la suppression',
    'pleaseEnterQRCode': 'Veuillez entrer un QR code',
    'enterQRCode': 'Entrez le QR Code',
    'submit': 'Soumettre',
    'cancel': 'Annuler',
    'settings': 'Paramètres',
    'language': 'Langue',
    'english': 'Anglais',
    'french': 'Français',
    'logout': 'Déconnexion',
    'logoutConfirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'yes': 'Oui',
    'no': 'Non',
    'about': 'À propos',
    'version': 'Version',
    'buildNumber': 'Numéro de build',
    'deviceInfo': 'Informations sur l\'appareil',
    'deviceModel': 'Modèle d\'appareil',
    'osVersion': 'Version OS',
    'flutterVersion': 'Version Flutter',
    'dartVersion': 'Version Dart',
    'close': 'Fermer',
    'noRecordsFound': 'Aucun enregistrement trouvé',
    'clearHistory': 'Effacer l\'historique',
    'clearHistoryConfirm': 'Êtes-vous sûr de vouloir effacer tout l\'historique des scans ?',
    'historyCleared': 'Historique effacé',
    'errorClearingHistory': 'Erreur lors de l\'effacement de l\'historique',
    'exportHistory': 'Exporter l\'historique',
    'csvExportReady': 'Export CSV prêt ({0} caractères)',
    'errorExportingCsv': 'Erreur lors de l\'export CSV : {0}',
    'qrCodeScanned': 'QR code scanné : {0}',
    'errorScanningQrCode': 'Erreur lors du scan du QR code : {0}',
    'errorValidatingQrCode': 'Erreur lors de la validation du QR code : {0}',
    'noSpecificAccessInfo': 'Aucune information d\'accès spécifique disponible pour ce cas.',
    'errorWithDetails': 'Erreur : {0}',
    'qrCode': 'QR Code',
    'result': 'Résultat',
    'timestamp': 'Horodatage',
    'agent': 'Agent',
    'event': 'Événement',
    'venue': 'Lieu',
    'subscriptionInfo': 'Informations d\'abonnement',
    'userInfo': 'Informations utilisateur',
    'accessPoint': 'Point d\'accès',
    'price': 'Prix',
    'currency': 'Devise',
    'holderName': 'Nom du titulaire',
    'scanResult': 'Résultat du scan',
    'validationTime': 'Temps de validation',
    'denialDetails': 'Détails du refus',
    'lastUsage': 'Dernière utilisation',
    'entryPoint': 'Point d\'entrée',
    'primaryReason': 'Raison principale',
    'technicalReason': 'Raison technique',
    'suggestedActions': 'Actions suggérées',
    'contactInfo': 'Informations de contact',
    'supervisorPhone': 'Téléphone superviseur',
    'customerService': 'Service client',
    'justNow': 'À l\'instant',
    'minutesAgo': 'minutes',
    'hoursAgo': 'heures',
    'hourAgo': 'heure',
    'at': 'à',
    'unknown': 'Inconnu',
    'notAvailable': 'N/A',
    'noPlan': 'Aucun plan',
    'noData': 'Aucune donnée',
    'scanningInProgress': 'Scan en cours...',
    'pleaseWait': 'Veuillez patienter...',
    'connectionError': 'Erreur de connexion',
    'networkUnavailable': 'Réseau indisponible',
    'tryAgain': 'Réessayer',
    'refresh': 'Actualiser',
    'pullToRefresh': 'Tirez pour actualiser',
    'lastUpdated': 'Dernière mise à jour',
    'noInternetConnection': 'Pas de connexion internet',
    'checkConnection': 'Veuillez vérifier votre connexion internet et réessayer',
    'timeout': 'Délai d\'attente dépassé',
    'serverError': 'Erreur serveur',
    'badRequest': 'Mauvaise requête',
    'unauthorized': 'Non autorisé',
    'forbidden': 'Interdit',
    'notFound': 'Non trouvé',
    'internalServerError': 'Erreur interne du serveur',
    'serviceUnavailable': 'Service indisponible',
    'currentEvent': 'Événement actuel',
    'eventName': 'Nom de l\'événement',
    'eventDescription': 'Description de l\'événement',
    'noActiveEventsFound': 'Aucun événement actif trouvé',
    'userProfile': 'Profil utilisateur',
    'accessLevel': 'Niveau d\'accès',
    'agentId': 'ID de l\'agent',
    'deviceInformation': 'Informations sur l\'appareil',
    'appVersion': 'Version de l\'app',
    'lastLogin': 'Dernière connexion',
    'sessionInfo': 'Informations de session',
    'toggleMode': 'Basculer le mode',
    'flashOn': 'Flash activé',
    'flashOff': 'Flash désactivé',
    'frontCamera': 'Caméra avant',
    'backCamera': 'Caméra arrière',
    'scanCooldown': 'Délai de scan',
    'duplicateScan': 'Scan en double',
    'scanTooFast': 'Veuillez attendre avant de scanner à nouveau',
    'cameraPermission': 'Permission caméra',
    'cameraPermissionRequired': 'La permission caméra est requise pour scanner les QR codes',
    'grantPermission': 'Accorder la permission',
    'permissionDenied': 'Permission refusée',
    'permissionPermanentlyDenied': 'Permission définitivement refusée',
    'openSettings': 'Ouvrir les paramètres',
    'validationResult': 'Résultat de validation',
    'backToScanner': 'Retour au scanner',
    'scanAgain': 'Scanner à nouveau',
    'scanNewCode': 'Scanner un nouveau code',
    'validationDetails': 'Détails de validation',
    'accessGrantedTitle': 'Accès accordé',
    'accessDeniedTitle': 'Accès refusé',
    'infoModeTitle': 'Mode info',
    'scanInformation': 'Informations de scan',
    'debugLogs': 'Journaux de débogage',
    'scanHistory': 'Historique des scans',
    'scanStatistics': 'Statistiques de scan',
    'totalRecords': 'Total des enregistrements',
    'filterRecords': 'Filtrer les enregistrements',
    'sortBy': 'Trier par',
    'sortByDate': 'Trier par date',
    'sortByStatus': 'Trier par statut',
    'sortByAgent': 'Trier par agent',
    'ascending': 'Croissant',
    'descending': 'Décroissant',
    'noScansToday': 'Aucun scan aujourd\'hui',
    'scansThisWeek': 'Scans cette semaine',
    'scansThisMonth': 'Scans ce mois',
    'averageScanTime': 'Temps de scan moyen',
    'fastestScan': 'Scan le plus rapide',
    'slowestScan': 'Scan le plus lent',
    'scanTrends': 'Tendances de scan',
    'dailyStats': 'Statistiques quotidiennes',
    'weeklyStats': 'Statistiques hebdomadaires',
    'monthlyStats': 'Statistiques mensuelles',
    'contactAdministrator': 'Contactez votre administrateur pour configurer les événements',
    'entrixScanner': 'Entrix Scanner',
    'errorLoadingHistory': 'Erreur lors du chargement de l\'historique',
    'valid': 'Valide',
    'backToDashboard': 'Retour au tableau de bord',
    'codeLabel': 'Code :',
    'statusCodeLabel': 'Code de statut :',
    'checkQRCodeValidation': '• Le QR code est valide et non expiré\n• Vous avez une authentification appropriée\n• Le service backend fonctionne\n• La connexion réseau est disponible',
    'noActiveSubscription': 'Aucun abonnement actif',
    'subscriptionExpired': 'Abonnement expiré',
    'accessDenied': 'Accès refusé',
    'codeNotRecognized': 'Code non reconnu',
    'qrCodeNotValid': 'QR Code non valide',
    'startScanningToSeeHistory': 'Commencez à scanner des QR codes pour voir votre historique ici',
    'alreadyUsed': 'Déjà utilisé',
    'expired': 'Expiré',
    'all': 'Tous',
    'success': 'Succès',
    'error': 'Erreur',
    'errorOccurred': 'Erreur est survenue',
    'errorOccurredWithDetails': 'Une erreur est survenue : {0}',
    'warning': 'Avertissement',
    'infoModeLabel': 'Mode info',
    'infoSuccess': 'Info succès',
    'infoNotFound': 'Info non trouvée',
    'totalScans': 'Total',
    'successfulScans': 'Succès',
    'failedScans': 'Échoués',
    'infoScans': 'Mode info',
    'todayScans': 'Aujourd\'hui',
    'qrScanner': 'Scanner QR',
    'validationMode': 'Mode de validation',
    'infoOnlyMode': 'Mode info uniquement',
    'infoModeOnly': 'Mode info uniquement (Rôle contrôleur)',
    'enterQrCodeManually': 'Entrez le QR code manuellement',
    'checkInfo': 'Vérifier les infos',
    'validateQrCode': 'Valider le QR code',
    'instructions': 'Instructions',
    'pointCameraAtQrOrEnterManuallyToCheckSubscription': 'Pointez votre caméra vers un QR code ou entrez le numéro de série pour vérifier les informations d\'abonnement',
    'pointCameraAtQrOrEnterManuallyToValidateAccess': 'Pointez votre caméra vers un QR code ou entrez le numéro de série pour valider l\'accès',
    'pointCameraAtQrOrEnterSerialNumberToCheckSubscription': 'Pointez votre caméra vers un QR code ou entrez le numéro de série pour vérifier les informations d\'abonnement',
    'pointCameraAtQrOrEnterSerialNumberToValidateAccess': 'Pointez votre caméra vers un QR code ou entrez le numéro de série pour valider l\'accès',
    'controllerRoleInfoOnlyNoAccessValidation': 'Rôle contrôleur : Mode info uniquement - pas de validation d\'accès',
    'infoOnly': 'Info uniquement',
    'validation': 'Validation',
    'role': 'Rôle',
    'scannerPaused': 'Scanner en pause',
    'switchCamera': 'Changer de caméra',
    'scannerRefreshed': 'Scanner actualisé',
    'manualInput': 'Saisie manuelle',
    'serialNumber': 'Numéro de série',
    'enterSerialNumberManually': 'Entrez le numéro de série 4 chiffres',
    'validateSerialNumber': 'Valider le numéro de série',
    'pleaseEnterSerialNumber': 'Veuillez entrer un numéro de série',
    'serialNumberMustBe4Digits': 'Le numéro de série doit être exactement 4 chiffres',
    'serialNumberNotFound': 'Numéro de série non trouvé',
    'errorFindingSerialNumber': 'Erreur lors de la recherche du numéro de série',
    'searchRecords': 'Rechercher les enregistrements',
    'enterSerialNumberOrQrCode': 'Entrez le numéro de série ou le QR code',
    'qrCodeNotRecognized': 'QR code non reconnu',
    'codeExpired': 'Code expiré',
    'wrongEvent': 'Événement incorrect',
    'wrongZone': 'Zone incorrecte',
    'wrongTime': 'Heure incorrecte',
    'accessBlocked': 'Accès bloqué',
    'technicalError': 'Erreur technique',
    'conditionalAccess': 'Accès conditionnel',
    'noMessage': 'Aucun message'
  };
}

// Extension for easy access to localized strings
extension LocalizationExtension on BuildContext {
  String l10n(String key) => AppLocalizations.of(this, key);
}
